# The build prefix records the libraries actually compiled, including overrides.
# aria's license arrives the same way as every other dependency: installed into
# share/licenses/aria by scripts/build.py and listed in the manifest.
if(ARIAREAD_RUNTIME_CONFIG)
    if(NOT EXISTS "${ARIAREAD_RUNTIME_CONFIG}")
        message(FATAL_ERROR "Runtime configuration is missing; reconfigure this build before packaging")
    endif()
    include("${ARIAREAD_RUNTIME_CONFIG}")
endif()
if(NOT ARIAREAD_DEPS_PREFIX)
    set(ARIAREAD_DEPS_PREFIX "${ARIAREAD_SOURCE_DIR}/build/deps/prefix")
endif()
if(NOT ARIAREAD_LICENSE_OUTPUT)
    message(FATAL_ERROR "ARIAREAD_LICENSE_OUTPUT is required")
endif()
foreach(required
        "${ARIAREAD_SOURCE_DIR}/LICENSE"
        "${ARIAREAD_SOURCE_DIR}/THIRD_PARTY_NOTICES.md"
        "${ARIAREAD_DEPS_PREFIX}/share/ariaread-deps/manifest.json")
    if(NOT EXISTS "${required}")
        message(FATAL_ERROR "License staging input is missing: ${required}")
    endif()
endforeach()
file(READ "${ARIAREAD_DEPS_PREFIX}/share/ariaread-deps/manifest.json" receipt)
string(JSON dependencies GET "${receipt}" dependencies)
string(JSON count LENGTH "${dependencies}")
if(count LESS 1)
    message(FATAL_ERROR "Dependency license inventory is empty")
endif()
math(EXPR last "${count} - 1")
foreach(index RANGE 0 ${last})
    string(JSON name GET "${dependencies}" ${index} name)
    string(JSON files LENGTH "${dependencies}" ${index} license_files)
    if(NOT name MATCHES "^[A-Za-z0-9_.-]+$" OR name STREQUAL "..")
        message(FATAL_ERROR "Invalid dependency name in license inventory")
    endif()
    if(files GREATER 0)
        math(EXPR file_last "${files} - 1")
        foreach(file_index RANGE 0 ${file_last})
            string(JSON filename GET "${dependencies}" ${index} license_files ${file_index})
            if(NOT filename MATCHES "^[A-Za-z0-9_.-]+$" OR filename STREQUAL ".."
                    OR NOT EXISTS "${ARIAREAD_DEPS_PREFIX}/share/licenses/${name}/${filename}")
                message(FATAL_ERROR "Missing or invalid license file for ${name}: ${filename}")
            endif()
        endforeach()
    endif()
endforeach()
# These subdirectories are generated by this script. Refresh them after
# validating every input, so removed upstream notices cannot survive an update.
file(MAKE_DIRECTORY "${ARIAREAD_LICENSE_OUTPUT}")
file(LOCK "${ARIAREAD_LICENSE_OUTPUT}/.ariaread-stage.lock" GUARD PROCESS TIMEOUT 120)
file(REMOVE_RECURSE "${ARIAREAD_LICENSE_OUTPUT}/dependencies"
    "${ARIAREAD_LICENSE_OUTPUT}/ariaread" "${ARIAREAD_LICENSE_OUTPUT}/toolchain")
foreach(index RANGE 0 ${last})
    string(JSON name GET "${dependencies}" ${index} name)
    string(JSON files LENGTH "${dependencies}" ${index} license_files)
    if(files GREATER 0)
        file(COPY "${ARIAREAD_DEPS_PREFIX}/share/licenses/${name}"
            DESTINATION "${ARIAREAD_LICENSE_OUTPUT}/dependencies")
    endif()
endforeach()
file(MAKE_DIRECTORY "${ARIAREAD_LICENSE_OUTPUT}/ariaread")
file(COPY "${ARIAREAD_SOURCE_DIR}/LICENSE" "${ARIAREAD_SOURCE_DIR}/THIRD_PARTY_NOTICES.md"
    DESTINATION "${ARIAREAD_LICENSE_OUTPUT}/ariaread")
# Export only public source/license metadata, never the receipt's machine paths,
# compiler environment, or installed-file inventory.
file(WRITE "${ARIAREAD_LICENSE_OUTPUT}/components.json" "${dependencies}\n")

if(ARIAREAD_MINGW AND ARIAREAD_CXX_COMPILER)
    get_filename_component(compiler_bin "${ARIAREAD_CXX_COMPILER}" DIRECTORY)
    get_filename_component(toolchain_prefix "${compiler_bin}" DIRECTORY)
    foreach(component gcc gcc-libs winpthreads)
        if(IS_DIRECTORY "${toolchain_prefix}/share/licenses/${component}")
            file(COPY "${toolchain_prefix}/share/licenses/${component}"
                DESTINATION "${ARIAREAD_LICENSE_OUTPUT}/toolchain")
        endif()
    endforeach()
    message(STATUS "MinGW runtime distribution: review the selected toolchain licenses and Runtime Library Exception; see THIRD_PARTY_NOTICES.md")
endif()
